In [4]:
deltaH = -541.5
deltaS = 10.4
temp = 298
deltaG = deltaH - temp*deltaS
print(deltaG)

-3640.7000000000003


In [5]:
deltaG_J = deltaG * 1000
print(deltaG)
print(deltaG_J)

-3640.7000000000003
-3640700.0000000005


In [6]:
deltaH, deltaS, temp = -541.5, 10.4, 298
deltaG = deltaH - temp*deltaS
print(deltaG)

-3640.7000000000003


In [7]:
energy_kcal = [-13.4, -2.7, 5.4, 42.1]
energy_length = len(energy_kcal)
print(energy_length)

4


In [8]:
slice1 = energy_kcal[1:]
slice2 = energy_kcal[:3]
print(slice1)
print(slice2)


[-2.7, 5.4, 42.1]
[-13.4, -2.7, 5.4]


In [10]:
energy_kJ = []
for number in energy_kcal:
    kJ = number*4.184
    energy_kJ.append(kJ)
    
print(energy_kJ)

[-56.0656, -11.296800000000001, 22.593600000000002, 176.1464]


In [11]:
negatives = []
for number in energy_kcal:
    if number < 0:
        negatives.append(number)
        
        
print(negatives)

[-13.4, -2.7]


In [12]:
pwd

'C:\\Users\\dadun\\Desktop\\cms-workshop\\data'

In [2]:
import os

In [14]:
ethanol_file = os.path.join('outfiles', 'ethanol.out')

In [15]:
outfile = open(ethanol_file, 'r')
data = outfile.readlines()
print(len(data))

270


In [16]:
for line in data:
    if 'Final Energy' in line:
        energy_line = line
        
print(energy_line)

  @DF-RHF Final Energy:  -154.09130176573018



In [19]:
words = energy_line.split()[-1]
print(words)

-154.09130176573018


In [18]:
words2 = energy_line.split(':')
print(words2)

['  @DF-RHF Final Energy', '  -154.09130176573018\n']


In [3]:
import glob


In [21]:
file_location = os.path.join('outfiles', '*.out')
filenames = glob.glob(file_location)
print(filenames)

['outfiles\\butanol.out', 'outfiles\\decanol.out', 'outfiles\\ethanol.out', 'outfiles\\heptanol.out', 'outfiles\\hexanol.out', 'outfiles\\methanol.out', 'outfiles\\nonanol.out', 'outfiles\\octanol.out', 'outfiles\\pentanol.out', 'outfiles\\propanol.out']


In [29]:
datafile = open('energies.txt', 'w+')


for file in filenames:
    outfile = open(file, 'r')
    data = outfile.readlines()
    outfile.close()
    for line in data:
        if 'Final Energy' in line:
            energy_line = line
            words = energy_line.split()[-1]
            energy = float(words)
            datafile.write(os.path.basename(file).split('.')[0] + str(energy) + '\n')
            
datafile.close()
            

In [4]:
import numpy 
distance_file = os.path.join('distance_data_headers.csv')
print(distance_file)

distances = numpy.genfromtxt(fname=distance_file, delimiter=',', dtype='unicode')


headers = distances[0]


data = distances[1:]
data = data.astype(numpy.float)
print(data)


distance_data_headers.csv
[[1.00000e+00 8.95420e+00 5.80240e+00 1.15478e+01 9.95570e+00]
 [2.00000e+00 8.61810e+00 6.09420e+00 1.39594e+01 1.16945e+01]
 [3.00000e+00 9.00660e+00 6.06370e+00 1.30924e+01 1.13043e+01]
 ...
 [9.99800e+03 8.66250e+00 7.73060e+00 9.54690e+00 1.03063e+01]
 [9.99900e+03 9.24560e+00 7.88860e+00 9.81510e+00 1.07564e+01]
 [1.00000e+04 8.81350e+00 7.91700e+00 9.95170e+00 1.07848e+01]]


In [35]:
print(data[0,1])


8.9542


In [36]:
small_data = data[0:10, 0:3]
print(small_data)

[[ 1.      8.9542  5.8024]
 [ 2.      8.6181  6.0942]
 [ 3.      9.0066  6.0637]
 [ 4.      9.2002  6.0227]
 [ 5.      9.1294  5.9365]
 [ 6.      9.0462  6.2553]
 [ 7.      8.8657  5.9186]
 [ 8.      9.3256  6.2351]
 [ 9.      9.4184  6.1993]
 [10.      9.06    6.0478]]


In [38]:
thr = data[:, 1]
print(thr)

[8.9542 8.6181 9.0066 ... 8.6625 9.2456 8.8135]


In [5]:
import pandas as pd
#get file
filename = os.path.join('water.xyz')

data = numpy.genfromtxt(fname=filename, dtype='unicode', skip_header=2)
print(data)



[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [9]:
names = data[:,0]
data = data[:, 1:].astype(numpy.float)
print(data)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [18]:
def bond_check(dist):
    return dist < 1.5

In [19]:

for i in range(colLen):
    for j in range(colLen):
        #get distance from i and j
        iRow = data[i,:]
        jRow = data[j,:]
        dist = calculate_distance(data[i,:], data[j,:])
        print(bond_check(dist))

    
    

True
True
True
True
True
False
True
False
True


In [11]:
colLen = len(data[1,:])
rowLen = len(data[:,1])

In [17]:
def calculate_distance(coords1, coords2):
    """ 
    This function accepts coordinates of two atoms and calculates the distance between atoms.
    """
    x_distance = coords1[0] - coords2[0]
    y_distance = coords1[1] - coords2[1]
    z_distance = coords1[2] - coords2[2]
    distance_12 = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
    return distance_12